"""
Verification script for Phase 2 Computer Vision Pipeline.
Runs the CVPipeline on synthetic frames generated by the DemoSimulator
to verify that all 10 modules integrate correctly, track state,
and execute without errors.
"""
import sys
import os
import time
import numpy as np

# Add backend app directory to python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.ai.pipeline import CVPipeline
from app.ai.camera.manager import DemoSimulator

def main():
    print("====================================================")
    print("   COGNITIVE CLASSROOM DIGITAL TWIN - PHASE 2 VERIFY")
    print("====================================================")
    print("Initializing full computer vision pipeline...")
    
    # Initialize pipeline with mock parameters
    pipeline = CVPipeline(
        detector_model_size="n",
        confidence_threshold=0.45,
        room_capacity=20,
        enable_face=True,
        enable_emotion=True,
        teacher_track_id=1,  # Assume track_id 1 is the teacher
    )
    
    # Initialize simulator
    simulator = DemoSimulator(resolution=(1280, 720), fps=15.0, n_students=8)
    
    # Warmup pipeline
    print("Warming up models...")
    pipeline.warmup()
    print("Warmup complete. Processing test sequence...")
    
    # Process 15 frames
    total_time = 0
    for frame_idx in range(1, 16):
        frame = simulator.generate_frame()
        audio_chunk = np.random.uniform(-0.01, 0.01, 1600).astype(np.float32)  # dummy audio chunk
        
        t0 = time.perf_counter()
        result = pipeline.process_frame(frame, audio_chunk)
        t1 = time.perf_counter()
        
        duration_ms = (t1 - t0) * 1000
        total_time += duration_ms
        
        print(f"Frame {frame_idx:02d}: Detected {len(result.persons)} persons | "
              f"Students: {result.student_count} | "
              f"Teacher: {'YES' if result.teacher_detected else 'NO'} | "
              f"Lighting: {result.environment['lighting']:.1f}% | "
              f"Noise: {result.environment['noise']:.1f}% | "
              f"Speed: {duration_ms:.1f}ms")
        
        # Verify frame output fields after tracking stabilizes
        if frame_idx == 5:
            if not result.persons:
                print("ERROR: No persons detected in frame 5!")
                sys.exit(1)
            
            p = result.persons[0]
            print("\nVerification of Snapshot Data Structure:")
            print(f"  - Track ID: {p.track_id}")
            print(f"  - Bounding Box: {p.bbox}")
            print(f"  - Seat ID: {p.seat_id}")
            print(f"  - Head Pose (Y,P,R): {p.head_yaw:.1f}, {p.head_pitch:.1f}, {p.head_roll:.1f}")
            print(f"  - Gaze Target: {p.gaze_target} (Conf: {p.gaze_confidence:.2f})")
            print(f"  - Dominant Emotion: {p.dominant_emotion} (Conf: {p.emotion_confidence:.2f})")
            print(f"  - Activity: {p.activity} (Conf: {p.activity_confidence:.2f})")
            print(f"  - Is Teacher: {p.is_teacher}")
            print("----------------------------------------------------\n")

    avg_time = total_time / 15
    print("====================================================")
    print("                  VERIFICATION RESULTS              ")
    print("====================================================")
    print(f"Total frames processed: 15")
    print(f"Average processing time per frame: {avg_time:.2f}ms")
    print(f"Pipeline status: PASSED [OK]")
    print("====================================================")

if __name__ == "__main__":
    main()
